name = "EmulatE"
uuid = "d8d8028b-a2d6-4981-bad3-a3e7b715ca60"
authors = ["Tom W Ouellette"]
version = "0.1.0"

[compat]
julia = "1.5.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
